/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import com.mxgraph.examples.swing.editor.EditorActions;
import com.mxgraph.model.SolutionBuild;
import com.mxgraph.model.YUHD;
import com.mxgraph.mysqlUtils.DaoSolution;
import com.mxgraph.mysqlUtils.DaoYUHD;
import com.mxgraph.util.mxConstants;
import com.util.FileOperate;
import com.util.JsonOperation;
import com.util.myConstants;
import static com.util.myConstants.cell;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class Softwear3 extends javax.swing.JPanel {

    private String proid = "";
    private String objid = "";
    private SolutionBuild model;

    /**
     * Creates new form Softwear3
     */
    public Softwear3() {
        initComponents();
        myConstants.jTabbedPane2 = this.jTabbedPane2;
        jTabbedPane2.setEnabled(false);
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        yewuhuodong = new javax.swing.JTextField();
        yewuhuodongbianhao = new javax.swing.JTextField();
        fuguocheng = new javax.swing.JTextField();
        huodongmiaoshu = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        qingjingmingcheng = new javax.swing.JTextField();
        zhixingzhe = new javax.swing.JTextField();
        shuchuchengguo = new javax.swing.JTextField();
        shijian = new javax.swing.JTextField();
        didian = new javax.swing.JTextField();
        biaozhun = new javax.swing.JTextField();
        fuzhusheshi = new javax.swing.JTextField();
        kongqihuanjing = new javax.swing.JTextField();
        kongjian = new javax.swing.JTextField();
        zuzhijili = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        yewuwentiqiujie = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        neirongmiaoshu = new javax.swing.JTextPane();

        jTabbedPane2.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jLabel1.setText("活动名称:");

        jLabel2.setText("业活动编号:");

        jLabel3.setText("父过程:");

        jLabel4.setText("活动描述:");

        yewuhuodong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yewuhuodongActionPerformed(evt);
            }
        });

        jButton1.setText("保存");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setLabel("选择");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton7.setText("业务问题情景");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton6.setText("资源建模");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(yewuhuodongbianhao, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(huodongmiaoshu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(fuguocheng, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yewuhuodong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(yewuhuodong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(yewuhuodongbianhao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fuguocheng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(huodongmiaoshu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton7)
                    .addComponent(jButton6))
                .addContainerGap(318, Short.MAX_VALUE))
        );

        jButton3.getAccessibleContext().setAccessibleName("fuguochengx2");

        jTabbedPane2.addTab("业务活动", jPanel2);

        jLabel5.setText("情景名称:");

        jLabel6.setText("执行者:");

        jLabel7.setText("输出成果:");

        jLabel8.setText("时间:");

        jLabel9.setText("地点:");

        jLabel10.setText("标准:");

        jLabel11.setText("辅助设施:");

        jLabel12.setText("空气环境:");

        jLabel13.setText("空间:");

        jLabel14.setText("组织激励：");

        qingjingmingcheng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qingjingmingchengActionPerformed(evt);
            }
        });

        jButton2.setText("保存");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("选择");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("选择");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        yewuwentiqiujie.setText("业务问题情景");
        yewuwentiqiujie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yewuwentiqiujieActionPerformed(evt);
            }
        });

        jButton8.setText("资源建模");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel15.setText("内容描述:");

        jScrollPane2.setViewportView(neirongmiaoshu);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(kongjian, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(kongqihuanjing)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(fuzhusheshi, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(qingjingmingcheng))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(shuchuchengguo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(shijian, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(didian, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(biaozhun, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                        .addComponent(zhixingzhe)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton8)
                                .addGap(18, 18, 18)
                                .addComponent(yewuwentiqiujie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane2))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(zuzhijili, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)
                                .addComponent(jButton5)))
                        .addGap(14, 14, 14))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(qingjingmingcheng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(zhixingzhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(shuchuchengguo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(shijian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(didian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(biaozhun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fuzhusheshi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(kongqihuanjing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(kongjian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(zuzhijili, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(yewuwentiqiujie)
                    .addComponent(jButton8))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("业务活动求解", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("yewuhuodongtab");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void yewuhuodongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yewuhuodongActionPerformed

    }//GEN-LAST:event_yewuhuodongActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            YUHD model = new YUHD();
            model.setProid(getProid());
            model.setObjid(getObjid());
            model.setHuodongmingcheng(getYewuhuodong().getText());
            model.setYwuhuodongbianhao(getYewuhuodongbianhao().getText());
            model.setFuguocheng(getFuguocheng().getText());
            model.setHuodongmiaoshu(getHuodongmiaoshu().getText());
            DaoYUHD.add(model);
        } catch (SQLException ex) {
            Logger.getLogger(Softwear3.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void qingjingmingchengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qingjingmingchengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qingjingmingchengActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:.
        JFileChooser jfc = new JFileChooser();
        jfc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        jfc.showDialog(new JLabel(), "选择");
        File file = jfc.getSelectedFile();
        if (file.isDirectory()) {
            System.out.println("文件夹:" + file.getAbsolutePath());
        } else if (file.isFile()) {
            try {
                huodongmiaoshu.setText(FileOperate.BufferedReaderDemo(file.getAbsolutePath()));
            } catch (IOException ex) {
                Logger.getLogger(Softwear3.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        System.out.println(jfc.getSelectedFile().getName());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:.
        JFileChooser jfc = new JFileChooser();
        jfc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        jfc.showDialog(new JLabel(), "选择");
        File file = jfc.getSelectedFile();
        if (file.isDirectory()) {
            System.out.println("文件夹:" + file.getAbsolutePath());
        } else if (file.isFile()) {
            try {
                biaozhun.setText(FileOperate.BufferedReaderDemo(file.getAbsolutePath()));
            } catch (IOException ex) {
                Logger.getLogger(Softwear3.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        System.out.println(jfc.getSelectedFile().getName());          // TODO add your handling code here:

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            //                            swRight.get
            String qingjingmingcheng = getQingjingmingcheng().getText();
            String zhixingzhe = getZhixingzhe().getText();
            String shuchuchegnguo = getShuchuchengguo().getText();
            String date = getShijian().getText();
            String place = getDidian().getText();
            String biaozhun = getBiaozhun().getText();
            String fuzhusheshi = getFuzhusheshi().getText();
            String kongqihuanjing = getKongqihuanjing().getText();
            String kongjian = getKongjian().getText();
            String zuzhijili = getZuzhijili().getText();
            String neirongmiao=getNeirongmiaoshu().getText();
            SolutionBuild model = new SolutionBuild();
            model.setProid(proid);
            model.setObjid(String.valueOf(objid));
            model.setQingjingmingcheng(qingjingmingcheng);
            model.setZhixingzhe(zhixingzhe);
            model.setShuchuchengguo(shuchuchegnguo);
            model.setDate(date);
            model.setPlace(place);
            model.setStandard(biaozhun);
            model.setFuzhusheshi(fuzhusheshi);
            model.setKongqihuanjing(kongqihuanjing);
            model.setKongjian(kongjian);
            model.setZuzhijili(zuzhijili);

            DaoSolution.addSolution(model);
        } catch (SQLException ex) {
            Logger.getLogger(Softwear3.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        if (getProid() == "" || getProid() == null) {
            setProid(myConstants.uuid);
        }
        myConstants.setCurrentProid(getProid());
        YeWu yewu = new YeWu();

        yewu.setBackground(Color.LIGHT_GRAY);

        yewu.setProid(getProid());
        yewu.tianchong();
        yewu.setProid(myConstants.getCurrentProid());
        yewu.setVisible(true);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void yewuwentiqiujieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yewuwentiqiujieActionPerformed
        // TODO add your handling code here:

        jButton7.doClick();
    }//GEN-LAST:event_yewuwentiqiujieActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        jfc.showDialog(new JLabel(), "选择");
        File file = jfc.getSelectedFile();
        if (file.isDirectory()) {
            System.out.println("文件夹:" + file.getAbsolutePath());
        } else if (file.isFile()) {
            try {
                zuzhijili.setText(FileOperate.BufferedReaderDemo(file.getAbsolutePath()));
            } catch (IOException ex) {
                Logger.getLogger(Softwear3.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        System.out.println(jfc.getSelectedFile().getName());         // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jButton8.doClick();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         new EditorActions.SoftwareActionThree().actionPerformed(evt);
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField biaozhun;
    private javax.swing.JTextField didian;
    private javax.swing.JTextField fuguocheng;
    private javax.swing.JTextField fuzhusheshi;
    private javax.swing.JTextField huodongmiaoshu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField kongjian;
    private javax.swing.JTextField kongqihuanjing;
    private javax.swing.JTextPane neirongmiaoshu;
    private javax.swing.JTextField qingjingmingcheng;
    private javax.swing.JTextField shijian;
    private javax.swing.JTextField shuchuchengguo;
    private javax.swing.JTextField yewuhuodong;
    private javax.swing.JTextField yewuhuodongbianhao;
    private javax.swing.JButton yewuwentiqiujie;
    private javax.swing.JTextField zhixingzhe;
    private javax.swing.JTextField zuzhijili;
    // End of variables declaration//GEN-END:variables
public static void main(String[] args) {

    }

    /**
     * @return the biaozhun
     */
    public javax.swing.JTextField getBiaozhun() {
        return biaozhun;
    }

    /**
     * @param biaozhun the biaozhun to set
     */
    public void setBiaozhun(javax.swing.JTextField biaozhun) {
        this.biaozhun = biaozhun;
    }

    /**
     * @return the didian
     */
    public javax.swing.JTextField getDidian() {
        return didian;
    }

    /**
     * @param didian the didian to set
     */
    public void setDidian(javax.swing.JTextField didian) {
        this.didian = didian;
    }

    /**
     * @return the fuguocheng
     */
    public javax.swing.JTextField getFuguocheng() {
        return fuguocheng;
    }

    /**
     * @param fuguocheng the fuguocheng to set
     */
    public void setFuguocheng(javax.swing.JTextField fuguocheng) {
        this.fuguocheng = fuguocheng;
    }

    /**
     * @return the fuzhusheshi
     */
    public javax.swing.JTextField getFuzhusheshi() {
        return fuzhusheshi;
    }

    /**
     * @param fuzhusheshi the fuzhusheshi to set
     */
    public void setFuzhusheshi(javax.swing.JTextField fuzhusheshi) {
        this.fuzhusheshi = fuzhusheshi;
    }

    /**
     * @return the huodongmiaoshu
     */
    public javax.swing.JTextField getHuodongmiaoshu() {
        return huodongmiaoshu;
    }

    /**
     * @param huodongmiaoshu the huodongmiaoshu to set
     */
    public void setHuodongmiaoshu(javax.swing.JTextField huodongmiaoshu) {
        this.huodongmiaoshu = huodongmiaoshu;
    }

    /**
     * @return the jButton1
     */
    public javax.swing.JButton getjButton1() {
        return jButton1;
    }

    /**
     * @param jButton1 the jButton1 to set
     */
    public void setjButton1(javax.swing.JButton jButton1) {
        this.jButton1 = jButton1;
    }

    /**
     * @return the jButton2
     */
    public javax.swing.JButton getjButton2() {
        return jButton2;
    }

    /**
     * @param jButton2 the jButton2 to set
     */
    public void setjButton2(javax.swing.JButton jButton2) {
        this.jButton2 = jButton2;
    }

    /**
     * @return the jButton3
     */
    public javax.swing.JButton getjButton3() {
        return jButton3;
    }

    /**
     * @param jButton3 the jButton3 to set
     */
    public void setjButton3(javax.swing.JButton jButton3) {
        this.jButton3 = jButton3;
    }

    /**
     * @return the jButton4
     */
    public javax.swing.JButton getjButton4() {
        return jButton4;
    }

    /**
     * @param jButton4 the jButton4 to set
     */
    public void setjButton4(javax.swing.JButton jButton4) {
        this.jButton4 = jButton4;
    }

    /**
     * @return the jButton5
     */
    public javax.swing.JButton getjButton5() {
        return jButton5;
    }

    /**
     * @param jButton5 the jButton5 to set
     */
    public void setjButton5(javax.swing.JButton jButton5) {
        this.jButton5 = jButton5;
    }

    /**
     * @return the jFileChooser1
     */
    public javax.swing.JFileChooser getjFileChooser1() {
        return jFileChooser1;
    }

    /**
     * @param jFileChooser1 the jFileChooser1 to set
     */
    public void setjFileChooser1(javax.swing.JFileChooser jFileChooser1) {
        this.jFileChooser1 = jFileChooser1;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    /**
     * @return the jLabel10
     */
    public javax.swing.JLabel getjLabel10() {
        return jLabel10;
    }

    /**
     * @param jLabel10 the jLabel10 to set
     */
    public void setjLabel10(javax.swing.JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    /**
     * @return the jLabel11
     */
    public javax.swing.JLabel getjLabel11() {
        return jLabel11;
    }

    /**
     * @param jLabel11 the jLabel11 to set
     */
    public void setjLabel11(javax.swing.JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    /**
     * @return the jLabel12
     */
    public javax.swing.JLabel getjLabel12() {
        return jLabel12;
    }

    /**
     * @param jLabel12 the jLabel12 to set
     */
    public void setjLabel12(javax.swing.JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    /**
     * @return the jLabel13
     */
    public javax.swing.JLabel getjLabel13() {
        return jLabel13;
    }

    /**
     * @param jLabel13 the jLabel13 to set
     */
    public void setjLabel13(javax.swing.JLabel jLabel13) {
        this.jLabel13 = jLabel13;
    }

    /**
     * @return the jLabel14
     */
    public javax.swing.JLabel getjLabel14() {
        return jLabel14;
    }

    /**
     * @param jLabel14 the jLabel14 to set
     */
    public void setjLabel14(javax.swing.JLabel jLabel14) {
        this.jLabel14 = jLabel14;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @param jLabel2 the jLabel2 to set
     */
    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    /**
     * @return the jLabel3
     */
    public javax.swing.JLabel getjLabel3() {
        return jLabel3;
    }

    /**
     * @param jLabel3 the jLabel3 to set
     */
    public void setjLabel3(javax.swing.JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    /**
     * @return the jLabel4
     */
    public javax.swing.JLabel getjLabel4() {
        return jLabel4;
    }

    /**
     * @param jLabel4 the jLabel4 to set
     */
    public void setjLabel4(javax.swing.JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    /**
     * @return the jLabel5
     */
    public javax.swing.JLabel getjLabel5() {
        return jLabel5;
    }

    /**
     * @param jLabel5 the jLabel5 to set
     */
    public void setjLabel5(javax.swing.JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    /**
     * @return the jLabel6
     */
    public javax.swing.JLabel getjLabel6() {
        return jLabel6;
    }

    /**
     * @param jLabel6 the jLabel6 to set
     */
    public void setjLabel6(javax.swing.JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    /**
     * @return the jLabel7
     */
    public javax.swing.JLabel getjLabel7() {
        return jLabel7;
    }

    /**
     * @param jLabel7 the jLabel7 to set
     */
    public void setjLabel7(javax.swing.JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    /**
     * @return the jLabel8
     */
    public javax.swing.JLabel getjLabel8() {
        return jLabel8;
    }

    /**
     * @param jLabel8 the jLabel8 to set
     */
    public void setjLabel8(javax.swing.JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    /**
     * @return the jLabel9
     */
    public javax.swing.JLabel getjLabel9() {
        return jLabel9;
    }

    /**
     * @param jLabel9 the jLabel9 to set
     */
    public void setjLabel9(javax.swing.JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the jPanel2
     */
    public javax.swing.JPanel getjPanel2() {
        return jPanel2;
    }

    /**
     * @param jPanel2 the jPanel2 to set
     */
    public void setjPanel2(javax.swing.JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    /**
     * @return the jPanel3
     */
    public javax.swing.JPanel getjPanel3() {
        return jPanel3;
    }

    /**
     * @param jPanel3 the jPanel3 to set
     */
    public void setjPanel3(javax.swing.JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    /**
     * @return the jTabbedPane2
     */
    public javax.swing.JTabbedPane getjTabbedPane2() {
        return jTabbedPane2;
    }

    /**
     * @param jTabbedPane2 the jTabbedPane2 to set
     */
    public void setjTabbedPane2(javax.swing.JTabbedPane jTabbedPane2) {
        this.jTabbedPane2 = jTabbedPane2;
    }

    /**
     * @return the kongjian
     */
    public javax.swing.JTextField getKongjian() {
        return kongjian;
    }

    /**
     * @param kongjian the kongjian to set
     */
    public void setKongjian(javax.swing.JTextField kongjian) {
        this.kongjian = kongjian;
    }

    /**
     * @return the kongqihuanjing
     */
    public javax.swing.JTextField getKongqihuanjing() {
        return kongqihuanjing;
    }

    /**
     * @param kongqihuanjing the kongqihuanjing to set
     */
    public void setKongqihuanjing(javax.swing.JTextField kongqihuanjing) {
        this.kongqihuanjing = kongqihuanjing;
    }

    /**
     * @return the qingjingmingcheng
     */
    public javax.swing.JTextField getQingjingmingcheng() {
        return qingjingmingcheng;
    }

    /**
     * @param qingjingmingcheng the qingjingmingcheng to set
     */
    public void setQingjingmingcheng(javax.swing.JTextField qingjingmingcheng) {
        this.qingjingmingcheng = qingjingmingcheng;
    }

    /**
     * @return the shijian
     */
    public javax.swing.JTextField getShijian() {
        return shijian;
    }

    /**
     * @param shijian the shijian to set
     */
    public void setShijian(javax.swing.JTextField shijian) {
        this.shijian = shijian;
    }

    /**
     * @return the shuchuchengguo
     */
    public javax.swing.JTextField getShuchuchengguo() {
        return shuchuchengguo;
    }

    /**
     * @param shuchuchengguo the shuchuchengguo to set
     */
    public void setShuchuchengguo(javax.swing.JTextField shuchuchengguo) {
        this.shuchuchengguo = shuchuchengguo;
    }

    /**
     * @return the yewuhuodong
     */
    public javax.swing.JTextField getYewuhuodong() {
        return yewuhuodong;
    }

    /**
     * @param yewuhuodong the yewuhuodong to set
     */
    public void setYewuhuodong(javax.swing.JTextField yewuhuodong) {
        this.yewuhuodong = yewuhuodong;
    }

    /**
     * @return the yewuhuodongbianhao
     */
    public javax.swing.JTextField getYewuhuodongbianhao() {
        return yewuhuodongbianhao;
    }

    /**
     * @param yewuhuodongbianhao the yewuhuodongbianhao to set
     */
    public void setYewuhuodongbianhao(javax.swing.JTextField yewuhuodongbianhao) {
        this.yewuhuodongbianhao = yewuhuodongbianhao;
    }

    /**
     * @return the zhixingzhe
     */
    public javax.swing.JTextField getZhixingzhe() {
        return zhixingzhe;
    }

    /**
     * @param zhixingzhe the zhixingzhe to set
     */
    public void setZhixingzhe(javax.swing.JTextField zhixingzhe) {
        this.zhixingzhe = zhixingzhe;
    }

    /**
     * @return the zuzhijili
     */
    public javax.swing.JTextField getZuzhijili() {
        return zuzhijili;
    }

    /**
     * @param zuzhijili the zuzhijili to set
     */
    public void setZuzhijili(javax.swing.JTextField zuzhijili) {
        this.zuzhijili = zuzhijili;
    }

    /**
     * @return the model
     */
    public SolutionBuild getModel() {
        return model;
    }

    /**
     * @param model the model to set
     */
    public void setModel(SolutionBuild model) {
        this.model = model;
    }

    /**
     * @return the proid
     */
    public String getProid() {
        return proid;
    }

    /**
     * @param proid the proid to set
     */
    public void setProid(String proid) {
        this.proid = proid;
    }

    /**
     * @return the objid
     */
    public String getObjid() {
        return objid;
    }

    /**
     * @param objid the objid to set
     */
    public void setObjid(String objid) {
        this.objid = objid;
    }

    /**
     * @return the neirongmiaoshu
     */
    public javax.swing.JTextPane getNeirongmiaoshu() {
        return neirongmiaoshu;
    }

    /**
     * @param neirongmiaoshu the neirongmiaoshu to set
     */
    public void setNeirongmiaoshu(javax.swing.JTextPane neirongmiaoshu) {
        this.neirongmiaoshu = neirongmiaoshu;
    }
}
