/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import com.mxgraph.model.Jisuanjiziyuan;
import com.mxgraph.model.KnowledgeUnit;
import com.mxgraph.model.Person;
import com.mxgraph.model.Ruanjianshebei;
import com.mxgraph.model.Tuwenziliao;
import com.mxgraph.model.Yingjianshebei;
import com.mxgraph.mysqlUtils.DaoJisuanjiziyuan;
import com.mxgraph.mysqlUtils.DaoKnowledgeUnit;
import com.mxgraph.mysqlUtils.DaoPerson;
import com.mxgraph.mysqlUtils.DaoRuanjianshebei;
import com.mxgraph.mysqlUtils.DaoTuwenziliao;
import com.mxgraph.mysqlUtils.DaoYingjianshebei;
import com.util.FileOperate;
import com.util.myConstants;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;

/**
 *
 * @author Administrator
 */
public class ThreePanel extends javax.swing.JPanel {

    private String proid;
    private String objid;

    /**
     * Creates new form ThreePanel
     */
    public ThreePanel() {
        initComponents();
        myConstants.jTabbedPaneThree = jTabbedPane1;
        shizhidanyuanSave.setEnabled(false);
        renyuanSave.setEnabled(true);
        tuwenziliaoSave.setEnabled(false);
        jisuanjiziyuanSave.setEnabled(false);
        ruanjianshebeiSave.setEnabled(false);
        yingjianshebeiSave.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "null"})
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Pname = new javax.swing.JTextField();
        Pnum = new javax.swing.JTextField();
        Plingyu = new javax.swing.JTextField();
        Pbumen = new javax.swing.JTextField();
        Pzhishineirong = new javax.swing.JTextField();
        Psuoshuzaiti = new javax.swing.JTextField();
        renyuanSave = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Tname = new javax.swing.JTextField();
        TAuthor = new javax.swing.JTextField();
        Tversion = new javax.swing.JTextField();
        Ttype = new javax.swing.JTextField();
        Tuseliyongli = new javax.swing.JTextField();
        tuwenziliaoSave = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        Twuliweizhi = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        JName = new javax.swing.JTextField();
        Jnum = new javax.swing.JTextField();
        JType = new javax.swing.JTextField();
        Jsource = new javax.swing.JTextField();
        Jcunfangweizhi = new javax.swing.JTextField();
        jisuanjiziyuanSave = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Rname = new javax.swing.JTextField();
        Rversion = new javax.swing.JTextField();
        Ryingyongfanwei = new javax.swing.JTextField();
        Ryingyongjiaocheng = new javax.swing.JTextField();
        Rwuliweizhi = new javax.swing.JTextField();
        ruanjianshebeiSave = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        Yname = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        Ytype = new javax.swing.JTextField();
        Yyingjianyaoqiu = new javax.swing.JTextField();
        Yyingyongjiaocheng = new javax.swing.JTextField();
        Ywuliweizhi = new javax.swing.JTextField();
        yingjianshebeiSave = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        zsdymingcheng = new javax.swing.JTextField();
        zsdybianhao = new javax.swing.JTextField();
        zsdylingyu = new javax.swing.JTextField();
        zsdyzhishineirong = new javax.swing.JTextField();
        zsdysuoshuzaiti = new javax.swing.JTextField();
        shizhidanyuanSave = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(372, 757));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));

        jLabel8.setText("姓名:");

        jLabel9.setText("工号:");

        jLabel10.setText("角色:");

        jLabel11.setText("部门:");

        jLabel12.setText("联系方式:");

        jLabel13.setText("素质信息:");

        renyuanSave.setText("保存");
        renyuanSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renyuanSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(renyuanSave)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)))
                            .addComponent(jLabel13)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pzhishineirong, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pbumen, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Plingyu, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Psuoshuzaiti, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                .addComponent(Pname)
                                .addComponent(Pnum)))))
                .addGap(0, 133, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Pname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Pnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Plingyu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Pbumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Pzhishineirong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Psuoshuzaiti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(renyuanSave))
        );

        jTabbedPane1.addTab("人员", jPanel3);

        jLabel14.setText("名称:");

        jLabel15.setText("作者:");

        jLabel16.setText("版本号:");

        jLabel17.setText("编号:");

        jLabel18.setText("可利用率:");

        tuwenziliaoSave.setText("保存");
        tuwenziliaoSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuwenziliaoSaveActionPerformed(evt);
            }
        });

        jLabel34.setText("物理位置:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tuwenziliaoSave)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabel16)
                                .addComponent(jLabel17)
                                .addComponent(jLabel15))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Tuseliyongli, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(TAuthor)
                                .addComponent(Tversion)
                                .addComponent(Ttype)
                                .addComponent(Tname))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(18, 18, 18)
                        .addComponent(Twuliweizhi)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Tname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(TAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Tversion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(Ttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(Tuseliyongli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(Twuliweizhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tuwenziliaoSave)
                .addContainerGap())
        );

        jTabbedPane1.addTab("图文资料", jPanel5);

        jLabel19.setText("名称:");

        jLabel20.setText("编号:");

        jLabel21.setText("类型:");

        jLabel22.setText("来源:");

        jLabel23.setText("存放位置:");

        jisuanjiziyuanSave.setText("保存");
        jisuanjiziyuanSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jisuanjiziyuanSaveActionPerformed(evt);
            }
        });

        jButton1.setText("选择");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(jisuanjiziyuanSave)
                .addGap(123, 123, 123))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jcunfangweizhi, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(JName))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(Jnum, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(JType))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(Jsource)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(JName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(Jnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(JType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(Jsource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(Jcunfangweizhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jisuanjiziyuanSave)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("计算机资源", jPanel6);

        jLabel24.setText("名称:");

        jLabel25.setText("版本:");

        jLabel26.setText("应用范围:");

        jLabel27.setText("应用教程:");

        jLabel28.setText("物理位置:");

        ruanjianshebeiSave.setText("保存");
        ruanjianshebeiSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruanjianshebeiSaveActionPerformed(evt);
            }
        });

        jButton8.setText("选择");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(Ryingyongjiaocheng, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel24))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Rname)
                                    .addComponent(Rversion)
                                    .addComponent(Ryingyongfanwei))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(Rwuliweizhi, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ruanjianshebeiSave)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(Rname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(Rversion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(Ryingyongfanwei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Ryingyongjiaocheng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(Rwuliweizhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ruanjianshebeiSave)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("软件设备", jPanel7);

        jLabel29.setText("名称");

        jLabel30.setText("型号");

        jLabel31.setText("硬件要求");

        jLabel32.setText("应用教程");

        jLabel33.setText("物理位置");

        yingjianshebeiSave.setText("保存");
        yingjianshebeiSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yingjianshebeiSaveActionPerformed(evt);
            }
        });

        jButton3.setText("选择");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(yingjianshebeiSave))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Yyingjianyaoqiu, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(Yyingyongjiaocheng, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Yname)
                            .addComponent(Ytype)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel33)
                        .addGap(18, 18, 18)
                        .addComponent(Ywuliweizhi, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(Yname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(Ytype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Yyingjianyaoqiu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Yyingyongjiaocheng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(Ywuliweizhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yingjianshebeiSave)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("硬件设备", jPanel8);

        jLabel1.setText("求解资源");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setForeground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("知识单元");

        jLabel3.setText("名称:");

        jLabel4.setText("编号:");

        jLabel5.setText("知识信息:");

        jLabel6.setText("知识内容:");

        jLabel7.setText("所属载体:");

        zsdybianhao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zsdybianhaoActionPerformed(evt);
            }
        });

        shizhidanyuanSave.setText("保存");
        shizhidanyuanSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shizhidanyuanSaveActionPerformed(evt);
            }
        });

        jButton2.setText("选择");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(zsdysuoshuzaiti, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(zsdyzhishineirong, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(zsdymingcheng))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(zsdybianhao))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(zsdylingyu)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shizhidanyuanSave)
                            .addComponent(jButton2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(zsdymingcheng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(zsdybianhao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(zsdylingyu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(zsdyzhishineirong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(zsdysuoshuzaiti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shizhidanyuanSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void shizhidanyuanSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shizhidanyuanSaveActionPerformed
        try {
            // TODO add your handling code here:

            String mingcheng = getZsdymingcheng().getText();
            String num = getZsdybianhao().getText();
            String area = getZsdylingyu().getText();
            String content = getZsdyzhishineirong().getText();
            String zaiti = getZsdysuoshuzaiti().getText();
            KnowledgeUnit model = new KnowledgeUnit();
            model.setMingcheng(mingcheng);
            model.setBianhao(num);
            model.setLingyu(area);
            model.setZhishineirong(content);
            model.setSuoshuzaiti(zaiti);
            model.setProid(getProid());
            model.setObjid(getObjid());
            DaoKnowledgeUnit.add(model);
        } catch (SQLException ex) {
            Logger.getLogger(ThreePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_shizhidanyuanSaveActionPerformed

    private void zsdybianhaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zsdybianhaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zsdybianhaoActionPerformed

    private void renyuanSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renyuanSaveActionPerformed
        try {
            // TODO add your handling code here:

            Person model = new Person();
            model.setProid(getProid());
            model.setObjid(getObjid());
            model.setXingming(getPname().getText());
            model.setGonghao(getPnum().getText());
            model.setLingyu(getPlingyu().getText());
            model.setBumen(getPbumen().getText());
            model.setZhishineirong(getPzhishineirong().getText());
            model.setSuoshuzaiti(getPsuoshuzaiti().getText());
            DaoPerson.add(model);

        } catch (SQLException ex) {
            Logger.getLogger(ThreePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_renyuanSaveActionPerformed

    private void tuwenziliaoSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuwenziliaoSaveActionPerformed
        try {
            // TODO add your handling code here:
            Tuwenziliao model = new Tuwenziliao();
            model.setMingcheng(getTname().getText());
            model.setZuozhe(getTAuthor().getText());
            model.setBanbenhao(getTversion().getText());
            model.setLeixing(getTtype().getText());
            model.setKeliyonglv(getTuseliyongli().getText());
            model.setWuliweizhi(getTwuliweizhi().getText());
            model.setProid(getProid());
            model.setObjid(getObjid());
            DaoTuwenziliao.add(model);
        } catch (SQLException ex) {
            Logger.getLogger(ThreePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tuwenziliaoSaveActionPerformed

    private void jisuanjiziyuanSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jisuanjiziyuanSaveActionPerformed
        // TODO add your handling code here:
        Jisuanjiziyuan model = new Jisuanjiziyuan();
        model.setProid(getProid());
        model.setObjid(getObjid());
        model.setMingcheng(getJName().getText());
        model.setBianhao(getJnum().getText());
        model.setLeixing(getJType().getText());
        model.setLaiyuan(getJsource().getText());
        model.setCunfangweizhi(getJcunfangweizhi().getText());
        try {
            DaoJisuanjiziyuan.add(model);
        } catch (SQLException ex) {
            Logger.getLogger(ThreePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jisuanjiziyuanSaveActionPerformed

    private void ruanjianshebeiSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruanjianshebeiSaveActionPerformed
        try {
            // TODO add your handling code here:
            Ruanjianshebei model = new Ruanjianshebei();
            model.setProid(getProid());
            model.setObjid(getObjid());
            model.setMingcheng(getRname().getText());
            model.setBanben(getRversion().getText());
            model.setYingyongfanwei(getRyingyongfanwei().getText());
            model.setYingyongjiaocheng(getRyingyongjiaocheng().getText());
            model.setWuliweizhi(getRwuliweizhi().getText());
            DaoRuanjianshebei.add(model);
        } catch (SQLException ex) {
            Logger.getLogger(ThreePanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ruanjianshebeiSaveActionPerformed

    private void yingjianshebeiSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yingjianshebeiSaveActionPerformed
        try {
            // TODO add your handling code here:
            Yingjianshebei model = new Yingjianshebei();
            model.setProid(getProid());
            model.setObjid(getObjid());
            model.setMingcheng(getYname().getText());
            model.setXinghao(getYtype().getText());
            model.setYingjianyaoqiu(getYyingjianyaoqiu().getText());
            model.setYingyongjiaocheng(getYyingyongjiaocheng().getText());
            model.setWuliweizhi(getYwuliweizhi().getText());
            DaoYingjianshebei.add(model);
        } catch (SQLException ex) {
            Logger.getLogger(ThreePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_yingjianshebeiSaveActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:.
        JFileChooser jfc = new JFileChooser();
        jfc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        jfc.showDialog(new JLabel(), "选择");
        File file = jfc.getSelectedFile();
        if (file.isDirectory()) {
            System.out.println("文件夹:" + file.getAbsolutePath());
        } else if (file.isFile()) {
            try {
                Ryingyongjiaocheng.setText(FileOperate.BufferedReaderDemo(file.getAbsolutePath()));
            } catch (IOException ex) {
                Logger.getLogger(Softwear3.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        System.out.println(jfc.getSelectedFile().getName());
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:.
        JFileChooser jfc = new JFileChooser();
        jfc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        jfc.showDialog(new JLabel(), "选择");
        File file = jfc.getSelectedFile();
        if (file.isDirectory()) {
            System.out.println("文件夹:" + file.getAbsolutePath());
        } else if (file.isFile()) {
            try {
                zsdyzhishineirong.setText(FileOperate.BufferedReaderDemo(file.getAbsolutePath()));
            } catch (IOException ex) {
                Logger.getLogger(Softwear3.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        System.out.println(jfc.getSelectedFile().getName());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:.
        JFileChooser jfc = new JFileChooser();
        jfc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        jfc.showDialog(new JLabel(), "选择");
        File file = jfc.getSelectedFile();
        if (file.isDirectory()) {
            System.out.println("文件夹:" + file.getAbsolutePath());
        } else if (file.isFile()) {
            try {
                Jcunfangweizhi.setText(FileOperate.BufferedReaderDemo(file.getAbsolutePath()));
            } catch (IOException ex) {
                Logger.getLogger(Softwear3.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        System.out.println(jfc.getSelectedFile().getName());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        jfc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        jfc.showDialog(new JLabel(), "选择");
        File file = jfc.getSelectedFile();
        if (file.isDirectory()) {
            System.out.println("文件夹:" + file.getAbsolutePath());
        } else if (file.isFile()) {
            try {
                Yyingyongjiaocheng.setText(FileOperate.BufferedReaderDemo(file.getAbsolutePath()));
            } catch (IOException ex) {
                Logger.getLogger(Softwear3.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        System.out.println(jfc.getSelectedFile().getName());
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JName;
    private javax.swing.JTextField JType;
    private javax.swing.JTextField Jcunfangweizhi;
    private javax.swing.JTextField Jnum;
    private javax.swing.JTextField Jsource;
    private javax.swing.JTextField Pbumen;
    private javax.swing.JTextField Plingyu;
    private javax.swing.JTextField Pname;
    private javax.swing.JTextField Pnum;
    private javax.swing.JTextField Psuoshuzaiti;
    private javax.swing.JTextField Pzhishineirong;
    private javax.swing.JTextField Rname;
    private javax.swing.JTextField Rversion;
    private javax.swing.JTextField Rwuliweizhi;
    private javax.swing.JTextField Ryingyongfanwei;
    private javax.swing.JTextField Ryingyongjiaocheng;
    private javax.swing.JTextField TAuthor;
    private javax.swing.JTextField Tname;
    private javax.swing.JTextField Ttype;
    private javax.swing.JTextField Tuseliyongli;
    private javax.swing.JTextField Tversion;
    private javax.swing.JTextField Twuliweizhi;
    private javax.swing.JTextField Yname;
    private javax.swing.JTextField Ytype;
    private javax.swing.JTextField Ywuliweizhi;
    private javax.swing.JTextField Yyingjianyaoqiu;
    private javax.swing.JTextField Yyingyongjiaocheng;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jisuanjiziyuanSave;
    private javax.swing.JButton renyuanSave;
    private javax.swing.JButton ruanjianshebeiSave;
    private javax.swing.JButton shizhidanyuanSave;
    private javax.swing.JButton tuwenziliaoSave;
    private javax.swing.JButton yingjianshebeiSave;
    private javax.swing.JTextField zsdybianhao;
    private javax.swing.JTextField zsdylingyu;
    private javax.swing.JTextField zsdymingcheng;
    private javax.swing.JTextField zsdysuoshuzaiti;
    private javax.swing.JTextField zsdyzhishineirong;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the proid
     */
    public String getProid() {
        return proid;
    }

    /**
     * @param proid the proid to set
     */
    public void setProid(String proid) {
        this.proid = proid;
    }

    /**
     * @return the objid
     */
    public String getObjid() {
        return objid;
    }

    /**
     * @param objid the objid to set
     */
    public void setObjid(String objid) {
        this.objid = objid;
    }

    /**
     * @return the JName
     */
    public javax.swing.JTextField getJName() {
        return JName;
    }

    /**
     * @param JName the JName to set
     */
    public void setJName(javax.swing.JTextField JName) {
        this.JName = JName;
    }

    /**
     * @return the JType
     */
    public javax.swing.JTextField getJType() {
        return JType;
    }

    /**
     * @param JType the JType to set
     */
    public void setJType(javax.swing.JTextField JType) {
        this.JType = JType;
    }

    /**
     * @return the Jcunfangweizhi
     */
    public javax.swing.JTextField getJcunfangweizhi() {
        return Jcunfangweizhi;
    }

    /**
     * @param Jcunfangweizhi the Jcunfangweizhi to set
     */
    public void setJcunfangweizhi(javax.swing.JTextField Jcunfangweizhi) {
        this.Jcunfangweizhi = Jcunfangweizhi;
    }

    /**
     * @return the Jnum
     */
    public javax.swing.JTextField getJnum() {
        return Jnum;
    }

    /**
     * @param Jnum the Jnum to set
     */
    public void setJnum(javax.swing.JTextField Jnum) {
        this.Jnum = Jnum;
    }

    /**
     * @return the Jsource
     */
    public javax.swing.JTextField getJsource() {
        return Jsource;
    }

    /**
     * @param Jsource the Jsource to set
     */
    public void setJsource(javax.swing.JTextField Jsource) {
        this.Jsource = Jsource;
    }

    /**
     * @return the Pbumen
     */
    public javax.swing.JTextField getPbumen() {
        return Pbumen;
    }

    /**
     * @param Pbumen the Pbumen to set
     */
    public void setPbumen(javax.swing.JTextField Pbumen) {
        this.Pbumen = Pbumen;
    }

    /**
     * @return the Plingyu
     */
    public javax.swing.JTextField getPlingyu() {
        return Plingyu;
    }

    /**
     * @param Plingyu the Plingyu to set
     */
    public void setPlingyu(javax.swing.JTextField Plingyu) {
        this.Plingyu = Plingyu;
    }

    /**
     * @return the Pname
     */
    public javax.swing.JTextField getPname() {
        return Pname;
    }

    /**
     * @param Pname the Pname to set
     */
    public void setPname(javax.swing.JTextField Pname) {
        this.Pname = Pname;
    }

    /**
     * @return the Pnum
     */
    public javax.swing.JTextField getPnum() {
        return Pnum;
    }

    /**
     * @param Pnum the Pnum to set
     */
    public void setPnum(javax.swing.JTextField Pnum) {
        this.Pnum = Pnum;
    }

    /**
     * @return the Psuoshuzaiti
     */
    public javax.swing.JTextField getPsuoshuzaiti() {
        return Psuoshuzaiti;
    }

    /**
     * @param Psuoshuzaiti the Psuoshuzaiti to set
     */
    public void setPsuoshuzaiti(javax.swing.JTextField Psuoshuzaiti) {
        this.Psuoshuzaiti = Psuoshuzaiti;
    }

    /**
     * @return the Pzhishineirong
     */
    public javax.swing.JTextField getPzhishineirong() {
        return Pzhishineirong;
    }

    /**
     * @param Pzhishineirong the Pzhishineirong to set
     */
    public void setPzhishineirong(javax.swing.JTextField Pzhishineirong) {
        this.Pzhishineirong = Pzhishineirong;
    }

    /**
     * @return the Rname
     */
    public javax.swing.JTextField getRname() {
        return Rname;
    }

    /**
     * @param Rname the Rname to set
     */
    public void setRname(javax.swing.JTextField Rname) {
        this.Rname = Rname;
    }

    /**
     * @return the Rversion
     */
    public javax.swing.JTextField getRversion() {
        return Rversion;
    }

    /**
     * @param Rversion the Rversion to set
     */
    public void setRversion(javax.swing.JTextField Rversion) {
        this.Rversion = Rversion;
    }

    /**
     * @return the Rwuliweizhi
     */
    public javax.swing.JTextField getRwuliweizhi() {
        return Rwuliweizhi;
    }

    /**
     * @param Rwuliweizhi the Rwuliweizhi to set
     */
    public void setRwuliweizhi(javax.swing.JTextField Rwuliweizhi) {
        this.Rwuliweizhi = Rwuliweizhi;
    }

    /**
     * @return the Ryingyongfanwei
     */
    public javax.swing.JTextField getRyingyongfanwei() {
        return Ryingyongfanwei;
    }

    /**
     * @param Ryingyongfanwei the Ryingyongfanwei to set
     */
    public void setRyingyongfanwei(javax.swing.JTextField Ryingyongfanwei) {
        this.Ryingyongfanwei = Ryingyongfanwei;
    }

    /**
     * @return the Ryingyongjiaocheng
     */
    public javax.swing.JTextField getRyingyongjiaocheng() {
        return Ryingyongjiaocheng;
    }

    /**
     * @param Ryingyongjiaocheng the Ryingyongjiaocheng to set
     */
    public void setRyingyongjiaocheng(javax.swing.JTextField Ryingyongjiaocheng) {
        this.Ryingyongjiaocheng = Ryingyongjiaocheng;
    }

    /**
     * @return the TAuthor
     */
    public javax.swing.JTextField getTAuthor() {
        return TAuthor;
    }

    /**
     * @param TAuthor the TAuthor to set
     */
    public void setTAuthor(javax.swing.JTextField TAuthor) {
        this.TAuthor = TAuthor;
    }

    /**
     * @return the Tname
     */
    public javax.swing.JTextField getTname() {
        return Tname;
    }

    /**
     * @param Tname the Tname to set
     */
    public void setTname(javax.swing.JTextField Tname) {
        this.Tname = Tname;
    }

    /**
     * @return the Ttype
     */
    public javax.swing.JTextField getTtype() {
        return Ttype;
    }

    /**
     * @param Ttype the Ttype to set
     */
    public void setTtype(javax.swing.JTextField Ttype) {
        this.Ttype = Ttype;
    }

    /**
     * @return the Tuseliyongli
     */
    public javax.swing.JTextField getTuseliyongli() {
        return Tuseliyongli;
    }

    /**
     * @param Tuseliyongli the Tuseliyongli to set
     */
    public void setTuseliyongli(javax.swing.JTextField Tuseliyongli) {
        this.Tuseliyongli = Tuseliyongli;
    }

    /**
     * @return the Tversion
     */
    public javax.swing.JTextField getTversion() {
        return Tversion;
    }

    /**
     * @param Tversion the Tversion to set
     */
    public void setTversion(javax.swing.JTextField Tversion) {
        this.Tversion = Tversion;
    }

    /**
     * @return the Twuliweizhi
     */
    public javax.swing.JTextField getTwuliweizhi() {
        return Twuliweizhi;
    }

    /**
     * @param Twuliweizhi the Twuliweizhi to set
     */
    public void setTwuliweizhi(javax.swing.JTextField Twuliweizhi) {
        this.Twuliweizhi = Twuliweizhi;
    }

    /**
     * @return the Yname
     */
    public javax.swing.JTextField getYname() {
        return Yname;
    }

    /**
     * @param Yname the Yname to set
     */
    public void setYname(javax.swing.JTextField Yname) {
        this.Yname = Yname;
    }

    /**
     * @return the Ytype
     */
    public javax.swing.JTextField getYtype() {
        return Ytype;
    }

    /**
     * @param Ytype the Ytype to set
     */
    public void setYtype(javax.swing.JTextField Ytype) {
        this.Ytype = Ytype;
    }

    /**
     * @return the Ywuliweizhi
     */
    public javax.swing.JTextField getYwuliweizhi() {
        return Ywuliweizhi;
    }

    /**
     * @param Ywuliweizhi the Ywuliweizhi to set
     */
    public void setYwuliweizhi(javax.swing.JTextField Ywuliweizhi) {
        this.Ywuliweizhi = Ywuliweizhi;
    }

    /**
     * @return the Yyingjianyaoqiu
     */
    public javax.swing.JTextField getYyingjianyaoqiu() {
        return Yyingjianyaoqiu;
    }

    /**
     * @param Yyingjianyaoqiu the Yyingjianyaoqiu to set
     */
    public void setYyingjianyaoqiu(javax.swing.JTextField Yyingjianyaoqiu) {
        this.Yyingjianyaoqiu = Yyingjianyaoqiu;
    }

    /**
     * @return the Yyingyongjiaocheng
     */
    public javax.swing.JTextField getYyingyongjiaocheng() {
        return Yyingyongjiaocheng;
    }

    /**
     * @param Yyingyongjiaocheng the Yyingyongjiaocheng to set
     */
    public void setYyingyongjiaocheng(javax.swing.JTextField Yyingyongjiaocheng) {
        this.Yyingyongjiaocheng = Yyingyongjiaocheng;
    }

    /**
     * @return the jButton1
     */
    public javax.swing.JButton getjButton1() {
        return getShizhidanyuanSave();
    }

    /**
     * @param jButton1 the jButton1 to set
     */
    public void setjButton1(javax.swing.JButton jButton1) {
        this.setShizhidanyuanSave(jButton1);
    }

    /**
     * @return the jButton2
     */
    public javax.swing.JButton getjButton2() {
        return jButton2;
    }

    /**
     * @param jButton2 the jButton2 to set
     */
    public void setjButton2(javax.swing.JButton jButton2) {
        this.jButton2 = jButton2;
    }

    /**
     * @return the jButton3
     */
    public javax.swing.JButton getjButton3() {
        return getTuwenziliaoSave();
    }

    /**
     * @param jButton3 the jButton3 to set
     */
    public void setjButton3(javax.swing.JButton jButton3) {
        this.setTuwenziliaoSave(jButton3);
    }

    /**
     * @return the jButton4
     */
    public javax.swing.JButton getjButton4() {
        return getJisuanjiziyuanSave();
    }

    /**
     * @param jButton4 the jButton4 to set
     */
    public void setjButton4(javax.swing.JButton jButton4) {
        this.setJisuanjiziyuanSave(jButton4);
    }

    /**
     * @return the jButton5
     */
    public javax.swing.JButton getjButton5() {
        return getRuanjianshebeiSave();
    }

    /**
     * @param jButton5 the jButton5 to set
     */
    public void setjButton5(javax.swing.JButton jButton5) {
        this.setRuanjianshebeiSave(jButton5);
    }

    /**
     * @return the jButton6
     */
    public javax.swing.JButton getjButton6() {
        return getYingjianshebeiSave();
    }

    /**
     * @param jButton6 the jButton6 to set
     */
    public void setjButton6(javax.swing.JButton jButton6) {
        this.setYingjianshebeiSave(jButton6);
    }

    /**
     * @return the jButton7
     */
    public javax.swing.JButton getjButton7() {
        return getRenyuanSave();
    }

    /**
     * @param jButton7 the jButton7 to set
     */
    public void setjButton7(javax.swing.JButton jButton7) {
        this.setRenyuanSave(jButton7);
    }

    /**
     * @return the jButton8
     */
    public javax.swing.JButton getjButton8() {
        return jButton8;
    }

    /**
     * @param jButton8 the jButton8 to set
     */
    public void setjButton8(javax.swing.JButton jButton8) {
        this.jButton8 = jButton8;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    /**
     * @return the jLabel10
     */
    public javax.swing.JLabel getjLabel10() {
        return jLabel10;
    }

    /**
     * @param jLabel10 the jLabel10 to set
     */
    public void setjLabel10(javax.swing.JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    /**
     * @return the jLabel11
     */
    public javax.swing.JLabel getjLabel11() {
        return jLabel11;
    }

    /**
     * @param jLabel11 the jLabel11 to set
     */
    public void setjLabel11(javax.swing.JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    /**
     * @return the jLabel12
     */
    public javax.swing.JLabel getjLabel12() {
        return jLabel12;
    }

    /**
     * @param jLabel12 the jLabel12 to set
     */
    public void setjLabel12(javax.swing.JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    /**
     * @return the jLabel13
     */
    public javax.swing.JLabel getjLabel13() {
        return jLabel13;
    }

    /**
     * @param jLabel13 the jLabel13 to set
     */
    public void setjLabel13(javax.swing.JLabel jLabel13) {
        this.jLabel13 = jLabel13;
    }

    /**
     * @return the jLabel14
     */
    public javax.swing.JLabel getjLabel14() {
        return jLabel14;
    }

    /**
     * @param jLabel14 the jLabel14 to set
     */
    public void setjLabel14(javax.swing.JLabel jLabel14) {
        this.jLabel14 = jLabel14;
    }

    /**
     * @return the jLabel15
     */
    public javax.swing.JLabel getjLabel15() {
        return jLabel15;
    }

    /**
     * @param jLabel15 the jLabel15 to set
     */
    public void setjLabel15(javax.swing.JLabel jLabel15) {
        this.jLabel15 = jLabel15;
    }

    /**
     * @return the jLabel16
     */
    public javax.swing.JLabel getjLabel16() {
        return jLabel16;
    }

    /**
     * @param jLabel16 the jLabel16 to set
     */
    public void setjLabel16(javax.swing.JLabel jLabel16) {
        this.jLabel16 = jLabel16;
    }

    /**
     * @return the jLabel17
     */
    public javax.swing.JLabel getjLabel17() {
        return jLabel17;
    }

    /**
     * @param jLabel17 the jLabel17 to set
     */
    public void setjLabel17(javax.swing.JLabel jLabel17) {
        this.jLabel17 = jLabel17;
    }

    /**
     * @return the jLabel18
     */
    public javax.swing.JLabel getjLabel18() {
        return jLabel18;
    }

    /**
     * @param jLabel18 the jLabel18 to set
     */
    public void setjLabel18(javax.swing.JLabel jLabel18) {
        this.jLabel18 = jLabel18;
    }

    /**
     * @return the jLabel19
     */
    public javax.swing.JLabel getjLabel19() {
        return jLabel19;
    }

    /**
     * @param jLabel19 the jLabel19 to set
     */
    public void setjLabel19(javax.swing.JLabel jLabel19) {
        this.jLabel19 = jLabel19;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @param jLabel2 the jLabel2 to set
     */
    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    /**
     * @return the jLabel20
     */
    public javax.swing.JLabel getjLabel20() {
        return jLabel20;
    }

    /**
     * @param jLabel20 the jLabel20 to set
     */
    public void setjLabel20(javax.swing.JLabel jLabel20) {
        this.jLabel20 = jLabel20;
    }

    /**
     * @return the jLabel21
     */
    public javax.swing.JLabel getjLabel21() {
        return jLabel21;
    }

    /**
     * @param jLabel21 the jLabel21 to set
     */
    public void setjLabel21(javax.swing.JLabel jLabel21) {
        this.jLabel21 = jLabel21;
    }

    /**
     * @return the jLabel22
     */
    public javax.swing.JLabel getjLabel22() {
        return jLabel22;
    }

    /**
     * @param jLabel22 the jLabel22 to set
     */
    public void setjLabel22(javax.swing.JLabel jLabel22) {
        this.jLabel22 = jLabel22;
    }

    /**
     * @return the jLabel23
     */
    public javax.swing.JLabel getjLabel23() {
        return jLabel23;
    }

    /**
     * @param jLabel23 the jLabel23 to set
     */
    public void setjLabel23(javax.swing.JLabel jLabel23) {
        this.jLabel23 = jLabel23;
    }

    /**
     * @return the jLabel24
     */
    public javax.swing.JLabel getjLabel24() {
        return jLabel24;
    }

    /**
     * @param jLabel24 the jLabel24 to set
     */
    public void setjLabel24(javax.swing.JLabel jLabel24) {
        this.jLabel24 = jLabel24;
    }

    /**
     * @return the jLabel25
     */
    public javax.swing.JLabel getjLabel25() {
        return jLabel25;
    }

    /**
     * @param jLabel25 the jLabel25 to set
     */
    public void setjLabel25(javax.swing.JLabel jLabel25) {
        this.jLabel25 = jLabel25;
    }

    /**
     * @return the jLabel26
     */
    public javax.swing.JLabel getjLabel26() {
        return jLabel26;
    }

    /**
     * @param jLabel26 the jLabel26 to set
     */
    public void setjLabel26(javax.swing.JLabel jLabel26) {
        this.jLabel26 = jLabel26;
    }

    /**
     * @return the jLabel27
     */
    public javax.swing.JLabel getjLabel27() {
        return jLabel27;
    }

    /**
     * @param jLabel27 the jLabel27 to set
     */
    public void setjLabel27(javax.swing.JLabel jLabel27) {
        this.jLabel27 = jLabel27;
    }

    /**
     * @return the jLabel28
     */
    public javax.swing.JLabel getjLabel28() {
        return jLabel28;
    }

    /**
     * @param jLabel28 the jLabel28 to set
     */
    public void setjLabel28(javax.swing.JLabel jLabel28) {
        this.jLabel28 = jLabel28;
    }

    /**
     * @return the jLabel29
     */
    public javax.swing.JLabel getjLabel29() {
        return jLabel29;
    }

    /**
     * @param jLabel29 the jLabel29 to set
     */
    public void setjLabel29(javax.swing.JLabel jLabel29) {
        this.jLabel29 = jLabel29;
    }

    /**
     * @return the jLabel3
     */
    public javax.swing.JLabel getjLabel3() {
        return jLabel3;
    }

    /**
     * @param jLabel3 the jLabel3 to set
     */
    public void setjLabel3(javax.swing.JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    /**
     * @return the jLabel30
     */
    public javax.swing.JLabel getjLabel30() {
        return jLabel30;
    }

    /**
     * @param jLabel30 the jLabel30 to set
     */
    public void setjLabel30(javax.swing.JLabel jLabel30) {
        this.jLabel30 = jLabel30;
    }

    /**
     * @return the jLabel31
     */
    public javax.swing.JLabel getjLabel31() {
        return jLabel31;
    }

    /**
     * @param jLabel31 the jLabel31 to set
     */
    public void setjLabel31(javax.swing.JLabel jLabel31) {
        this.jLabel31 = jLabel31;
    }

    /**
     * @return the jLabel32
     */
    public javax.swing.JLabel getjLabel32() {
        return jLabel32;
    }

    /**
     * @param jLabel32 the jLabel32 to set
     */
    public void setjLabel32(javax.swing.JLabel jLabel32) {
        this.jLabel32 = jLabel32;
    }

    /**
     * @return the jLabel33
     */
    public javax.swing.JLabel getjLabel33() {
        return jLabel33;
    }

    /**
     * @param jLabel33 the jLabel33 to set
     */
    public void setjLabel33(javax.swing.JLabel jLabel33) {
        this.jLabel33 = jLabel33;
    }

    /**
     * @return the jLabel34
     */
    public javax.swing.JLabel getjLabel34() {
        return jLabel34;
    }

    /**
     * @param jLabel34 the jLabel34 to set
     */
    public void setjLabel34(javax.swing.JLabel jLabel34) {
        this.jLabel34 = jLabel34;
    }

    /**
     * @return the jLabel4
     */
    public javax.swing.JLabel getjLabel4() {
        return jLabel4;
    }

    /**
     * @param jLabel4 the jLabel4 to set
     */
    public void setjLabel4(javax.swing.JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    /**
     * @return the jLabel5
     */
    public javax.swing.JLabel getjLabel5() {
        return jLabel5;
    }

    /**
     * @param jLabel5 the jLabel5 to set
     */
    public void setjLabel5(javax.swing.JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    /**
     * @return the jLabel6
     */
    public javax.swing.JLabel getjLabel6() {
        return jLabel6;
    }

    /**
     * @param jLabel6 the jLabel6 to set
     */
    public void setjLabel6(javax.swing.JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    /**
     * @return the jLabel7
     */
    public javax.swing.JLabel getjLabel7() {
        return jLabel7;
    }

    /**
     * @param jLabel7 the jLabel7 to set
     */
    public void setjLabel7(javax.swing.JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    /**
     * @return the jLabel8
     */
    public javax.swing.JLabel getjLabel8() {
        return jLabel8;
    }

    /**
     * @param jLabel8 the jLabel8 to set
     */
    public void setjLabel8(javax.swing.JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    /**
     * @return the jLabel9
     */
    public javax.swing.JLabel getjLabel9() {
        return jLabel9;
    }

    /**
     * @param jLabel9 the jLabel9 to set
     */
    public void setjLabel9(javax.swing.JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the jPanel2
     */
    public javax.swing.JPanel getjPanel2() {
        return jPanel2;
    }

    /**
     * @param jPanel2 the jPanel2 to set
     */
    public void setjPanel2(javax.swing.JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    /**
     * @return the jPanel3
     */
    public javax.swing.JPanel getjPanel3() {
        return jPanel3;
    }

    /**
     * @param jPanel3 the jPanel3 to set
     */
    public void setjPanel3(javax.swing.JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    /**
     * @return the jPanel4
     */
    public javax.swing.JPanel getjPanel4() {
        return jPanel4;
    }

    /**
     * @param jPanel4 the jPanel4 to set
     */
    public void setjPanel4(javax.swing.JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    /**
     * @return the jPanel5
     */
    public javax.swing.JPanel getjPanel5() {
        return jPanel5;
    }

    /**
     * @param jPanel5 the jPanel5 to set
     */
    public void setjPanel5(javax.swing.JPanel jPanel5) {
        this.jPanel5 = jPanel5;
    }

    /**
     * @return the jPanel6
     */
    public javax.swing.JPanel getjPanel6() {
        return jPanel6;
    }

    /**
     * @param jPanel6 the jPanel6 to set
     */
    public void setjPanel6(javax.swing.JPanel jPanel6) {
        this.jPanel6 = jPanel6;
    }

    /**
     * @return the jPanel7
     */
    public javax.swing.JPanel getjPanel7() {
        return jPanel7;
    }

    /**
     * @param jPanel7 the jPanel7 to set
     */
    public void setjPanel7(javax.swing.JPanel jPanel7) {
        this.jPanel7 = jPanel7;
    }

    /**
     * @return the jPanel8
     */
    public javax.swing.JPanel getjPanel8() {
        return jPanel8;
    }

    /**
     * @param jPanel8 the jPanel8 to set
     */
    public void setjPanel8(javax.swing.JPanel jPanel8) {
        this.jPanel8 = jPanel8;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the jTabbedPane1
     */
    public javax.swing.JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    /**
     * @param jTabbedPane1 the jTabbedPane1 to set
     */
    public void setjTabbedPane1(javax.swing.JTabbedPane jTabbedPane1) {
        this.jTabbedPane1 = jTabbedPane1;
    }

    /**
     * @return the zsdybianhao
     */
    public javax.swing.JTextField getZsdybianhao() {
        return zsdybianhao;
    }

    /**
     * @param zsdybianhao the zsdybianhao to set
     */
    public void setZsdybianhao(javax.swing.JTextField zsdybianhao) {
        this.zsdybianhao = zsdybianhao;
    }

    /**
     * @return the zsdylingyu
     */
    public javax.swing.JTextField getZsdylingyu() {
        return zsdylingyu;
    }

    /**
     * @param zsdylingyu the zsdylingyu to set
     */
    public void setZsdylingyu(javax.swing.JTextField zsdylingyu) {
        this.zsdylingyu = zsdylingyu;
    }

    /**
     * @return the zsdymingcheng
     */
    public javax.swing.JTextField getZsdymingcheng() {
        return zsdymingcheng;
    }

    /**
     * @param zsdymingcheng the zsdymingcheng to set
     */
    public void setZsdymingcheng(javax.swing.JTextField zsdymingcheng) {
        this.zsdymingcheng = zsdymingcheng;
    }

    /**
     * @return the zsdysuoshuzaiti
     */
    public javax.swing.JTextField getZsdysuoshuzaiti() {
        return zsdysuoshuzaiti;
    }

    /**
     * @param zsdysuoshuzaiti the zsdysuoshuzaiti to set
     */
    public void setZsdysuoshuzaiti(javax.swing.JTextField zsdysuoshuzaiti) {
        this.zsdysuoshuzaiti = zsdysuoshuzaiti;
    }

    /**
     * @return the zsdyzhishineirong
     */
    public javax.swing.JTextField getZsdyzhishineirong() {
        return zsdyzhishineirong;
    }

    /**
     * @param zsdyzhishineirong the zsdyzhishineirong to set
     */
    public void setZsdyzhishineirong(javax.swing.JTextField zsdyzhishineirong) {
        this.zsdyzhishineirong = zsdyzhishineirong;
    }

    /**
     * @return the jisuanjiziyuanSave
     */
    public javax.swing.JButton getJisuanjiziyuanSave() {
        return jisuanjiziyuanSave;
    }

    /**
     * @param jisuanjiziyuanSave the jisuanjiziyuanSave to set
     */
    public void setJisuanjiziyuanSave(javax.swing.JButton jisuanjiziyuanSave) {
        this.jisuanjiziyuanSave = jisuanjiziyuanSave;
    }

    /**
     * @return the renyuanSave
     */
    public javax.swing.JButton getRenyuanSave() {
        return renyuanSave;
    }

    /**
     * @param renyuanSave the renyuanSave to set
     */
    public void setRenyuanSave(javax.swing.JButton renyuanSave) {
        this.renyuanSave = renyuanSave;
    }

    /**
     * @return the ruanjianshebeiSave
     */
    public javax.swing.JButton getRuanjianshebeiSave() {
        return ruanjianshebeiSave;
    }

    /**
     * @param ruanjianshebeiSave the ruanjianshebeiSave to set
     */
    public void setRuanjianshebeiSave(javax.swing.JButton ruanjianshebeiSave) {
        this.ruanjianshebeiSave = ruanjianshebeiSave;
    }

    /**
     * @return the shizhidanyuanSave
     */
    public javax.swing.JButton getShizhidanyuanSave() {
        return shizhidanyuanSave;
    }

    /**
     * @param shizhidanyuanSave the shizhidanyuanSave to set
     */
    public void setShizhidanyuanSave(javax.swing.JButton shizhidanyuanSave) {
        this.shizhidanyuanSave = shizhidanyuanSave;
    }

    /**
     * @return the tuwenziliaoSave
     */
    public javax.swing.JButton getTuwenziliaoSave() {
        return tuwenziliaoSave;
    }

    /**
     * @param tuwenziliaoSave the tuwenziliaoSave to set
     */
    public void setTuwenziliaoSave(javax.swing.JButton tuwenziliaoSave) {
        this.tuwenziliaoSave = tuwenziliaoSave;
    }

    /**
     * @return the yingjianshebeiSave
     */
    public javax.swing.JButton getYingjianshebeiSave() {
        return yingjianshebeiSave;
    }

    /**
     * @param yingjianshebeiSave the yingjianshebeiSave to set
     */
    public void setYingjianshebeiSave(javax.swing.JButton yingjianshebeiSave) {
        this.yingjianshebeiSave = yingjianshebeiSave;
    }
}
